name: gesturetalk1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Tumhari existing dependencies
  cupertino_icons: ^1.0.8
  permission_handler:
  flutter_local_notifications: ^19.1.0
  torch_light: ^1.0.0
  vibration: ^3.1.3
  shared_preferences: ^2.0.15
  supabase_flutter: ^2.8.4
  gradient_borders: ^1.0.0
  reorderable_grid_view: ^2.2.8
  url_launcher: ^6.3.1
  flutter_contacts: ^1.1.7+1
  flutter_phone_direct_caller: ^2.2.1
  geolocator: ^14.0.1
  mailer: ^6.4.1
  location: ^8.0.0
  
  
  

  # Sir wali extra dependencies
  bottom_picker:
  country_code_picker:
  dropdown_button2:
  flutter_slidable:
  gap: ^3.0.1
  flutter_staggered_grid_view:
  table_calendar:
  syncfusion_flutter_sliders:
  svg_flutter:
  google_fonts:
  get:
  simple_gradient_text:
  weekly_date_picker:
  cached_network_image:
  intl:
  persistent_bottom_nav_bar:
  carousel_slider:
  pinput:
  bottom_navy_bar:
  stylish_bottom_bar:
  flutter_animate: ^4.5.2
  bounce: ^1.0.2
  intro_screen_onboarding_flutter: ^1.0.0
  smooth_page_indicator:
  syncfusion_flutter_charts: ^28.1.4
  fl_chart:
  draggable_home:
  flutter_advanced_drawer:
  tap_to_expand: ^0.7.2
  persistent_bottom_nav_bar_v2:
  dotted_border:
  flutter_spinkit: ^5.2.0
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^6.4.0
  lucide_icons: ^0.257.0
  
  youtube_player_flutter: ^9.1.1
  http: 1.3.0
  flutter_inappwebview: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/offline_voices/
    - assets/gestures.json
    - assets/offlinegestures/hello/
    - assets/offlinegestures/goodmorning/
    - assets/offlinegestures/help/
    - assets/offlinegestures/fire/
    - assets/offlinegestures/police/
    - assets/offlinegestures/hospital/
    - assets/offlinegestures/no/
    - assets/offlinegestures/yes/
    - assets/offlinegestures/toilet/
    - assets/offlinegestures/hungry/
    - assets/offlinegestures/water/
    - assets/offlinegestures/sick/
    - assets/offlinegestures/pain/
    - assets/offlinegestures/stop/
    - assets/offlinegestures/thankyou/
    - assets/offlinegestures/sorry/
    - assets/offlinegestures/donttouch/
    - assets/offlinegestures/goodbye/
    - assets/offlinegestures/please/
    - assets/offlinegestures/what/
    - assets/offlinegestures/where/
    - assets/offlinegestures/why/
    - assets/offlinegestures/how/
    - assets/offlinegestures/scared/
    - assets/offlinegestures/sad/
    - assets/offlinegestures/happy/
    - assets/offlinegestures/worried/
    - assets/offlinegestures/iloveyou/
    - assets/offlinegestures/mother/
    - assets/offlinegestures/father/
    - assets/offlinegestures/uncle/
    - assets/offlinegestures/aunt/
    - assets/offlinegestures/baby/
    - assets/offlinegestures/boy/
    - assets/offlinegestures/girl/
    - assets/offlinegestures/family/
    - assets/offlinegestures/home/
    - assets/offlinegestures/thief/
    - assets/offlinegestures/doctor/
    - assets/offlinegestures/school/
    - assets/offlinegestures/restaurant/
    - assets/offlinegestures/mosque/
    - assets/offlinegestures/church/
    - assets/offlinegestures/sleep/
    - assets/offlinegestures/lost/
    - assets/offlinegestures/cold/
    - assets/offlinegestures/angry/
    - assets/offlinegestures/quiet/
    - assets/offlinegestures/you'rwelcome/
    - assets/offlinegestures/want/
    - assets/offlinegestures/promise/
    - assets/offlinegestures/woww/
    - assets/offlinegestures/you/
    - assets/offlinegestures/good/
    - assets/offlinegestures/when/
    - assets/flags/
    - assets/flags/pakistan.png
    - assets/flags/uk.png
